export const SIGN_IN = 'SIGN_IN'

export const SIGN_OUT = 'SIGN_OUT'

export const CREATE_CURRENT_USER_ENTRY = 'CREATE_CURRENT_USER_ENTRY'

export const FETCH_CURRENT_USER_ENTRIES = 'FETCH_CURRENT_USER_ENTRIES'

export const UPDATE_CURRENT_USER_ENTRY = 'UPDATE_CURRENT_USER_ENTRY'

export const DELETE_CURRENT_USER_ENTRY = 'DELETE_CURRENT_USER_ENTRY' 